### PR TITLE
EEs-2234 remove metaguidance link from useful info

### PR DESCRIPTION
**Pull request by amyb-hiveit**
On the public frontend and the release edit / preview in the admin.

### CODE REVIEW

**Review by ntsim — COMMENTED** [review]
I'm guessing these changes could break the Robot tests - have you ran them?

**Comment by amyb-hiveit** [comment]
> I'm guessing these changes could break the Robot tests - have you ran them?

Doh, completely forgot them. On it now.

**Comment by amyb-hiveit** [comment]
I've updated the robot tests now but prerelease.robot has failing tests from 'Validate prerelease has started for Analyst user', they fail on dev for me as well as on this branch. I can't figure out what's up with them, it just stays on the dashboard it seems. @luke-h1 any ideas?

**Comment by luke-h1** [comment]
> I've updated the robot tests now but prerelease.robot has failing tests from 'Validate prerelease has started for Analyst user', they fail on dev for me as well as on this branch. I can't figure out what's up with them, it just stays on the dashboard it seems. @luke-h1 any ideas?

I'm not too sure why this is happening. I'll give this a look now

**Comment by luke-h1** [comment]
I've checked out to this branch and this test is passing in my local environment

**Review by luke-h1 — APPROVED** [review]

**Pull request merged**
