### PR TITLE
DFE-608 Add option to disable ESLint on save

### PR DESCRIPTION
**Pull request by ntsim**
This PR adds the environment variable option to disable ESLint on save as per our linting meeting last week.

Notably, you can disable it by adding the following to your `.env.local` (in your sub-projects):

```
ESLINT_DISABLE=true
```

### CODE REVIEW

**Comment by negatron99** [comment]
I thought we were going with disabled by default?
But if the option is easy enough to change, it's okay.

**Comment by ntsim** [comment]
Nope, don't think that was the agreement. It will be on by default and just toggled with an environment variable.

**Comment by jamescutts** [comment]
The agreement was disabled by default and that was reflected in the ticket in Jira, it looks like it should be easy enough to change.

**Comment by negatron99** [comment]
Also disabled when pushing on a branch into the repository and letting the PRs handle that when building.

**Comment by ntsim** [comment]
I don't remember any such agreement @jamescutts and I'm **never** going to endorse that linting is disabled by default for anyone that comes onto the project. If we need to discuss this again we can, but this PR should be sufficient for anyone that wants to disable the linting.

**Comment by shakes90** [comment]
Yeah I think this is perfectly acceptable tbh. It's easy to set as you wish so not too prescriptive. I really wouldn't disable it by default so gonna approve but let's have at least one more approver to be democratic :) otherwise it's another meet.

**Pull request merged**
